services:
  bestbuy-db:
    image: mongo:7.0
    container_name : bestbuy-db
    volumes:
      - bestbuy-data:/data/db
      - bestbuy-configdb:/data/configdb 
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - bestbuy-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout : 5s
      retries: 20

  bestbuy-backend:
    build:
      context: ./Server
    container_name : bestbuy-backend
    depends_on:
      bestbuy-db:
        condition: service_healthy
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8000:8000"
    networks:
      - bestbuy-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:8000 | grep -q 'HTTP/1.1 200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 20

  bestbuy-frontend:
    build:
      context: ./Client
      args:
        - VITE_APP_SERVER_URL=${VITE_APP_SERVER_URL}
    deploy:
      mode: replicated
      replicas: 3
    depends_on: 
      bestbuy-backend:
        condition: service_healthy
    environment:
      - VITE_APP_SERVER_URL
    ports:
      - "3000-3002:3000"
    networks:
      - bestbuy-network
    healthcheck:
      test : ["CMD-SHELL", "curl -s -I http://localhost:3000 | grep -q 'HTTP/1.1 200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 20
      
  nginx:
    image: nginx:latest
    container_name: bestbuy-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      bestbuy-frontend:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      - bestbuy-network


networks:
  bestbuy-network:
    external: true

volumes:
  bestbuy-data:
    external: true       #existing volume
  bestbuy-configdb:
    external: true       #existing network