services:
  bestbuy-db:
    image: mongo:7.0
    container_name: bestbuy-db
    volumes:
      - bestbuy-data:/data/db
      - bestbuy-configdb:/data/configdb
    secrets:
      - mongodb_db_name
      - mongodb_username
      - mongodb_password
    environment:
      - MONGO_INITDB_DATABASE_FILE=/run/secrets/mongodb_db_name
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
    ports:
      - "27017:27017"
    networks:
      - bestbuy-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 20

  bestbuy-backend:
    build:
      context: ./Server
    container_name: bestbuy-backend
    depends_on:
      bestbuy-db:
        condition: service_healthy
    secrets:
      - mongodb_uri
      - server_url
      - jwt_secret
    environment:
      - MONGODB_URI_FILE=/run/secrets/mongodb_uri
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - CLIENT_URL=${CLIENT_URL}
      - JWT_EXPIRE=${JWT_EXPIRE}
    ports:
      - "8000:8000"
    networks:
      - bestbuy-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:8000 | grep -q 'HTTP/1.1 200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 20

  bestbuy-frontend:
    secrets:
      - server_url
    build:
      context: ./Client
      args:
        - VITE_APP_SERVER_URL_FILE=/run/secrets/server_url
    container_name: bestbuy-frontend
    depends_on:
      bestbuy-backend:
        condition: service_healthy
    environment:
      - VITE_APP_SERVER_URL_FILE=/run/secrets/server_url
    ports:
      - "3000:3000"
    networks:
      - bestbuy-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:3000 | grep -q 'HTTP/1.1 200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 20

networks:
  bestbuy-network:
    external: true

volumes:
  bestbuy-data:
    external: true
  bestbuy-configdb:
    external: true

secrets:
  mongodb_db_name:
    file: ./Secrets/mongodb_db_name.txt
  mongodb_username:
    file: ./Secrets/mongodb_username.txt
  mongodb_password:
    file: ./Secrets/mongodb_password.txt
  mongodb_uri:
    file: ./Secrets/mongodb_uri.txt
  jwt_secret:
    file: ./Secrets/jwt_secret.txt
  server_url:
    file: ./Secrets/server_url.txt